Fix all lint issues checkout
saleor/react-storefront pull request #526
Opened 2022-10-12 08:16 UTC by bmigirl

2022-10-12 08:37 UTC, mmiszy commented on packages/checkout-storefront/src/hooks/useFormDebouncedSubmit.ts
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Why?

2022-10-12 08:37 UTC, mmiszy commented on packages/checkout-storefront/src/sections/UserAddressSection/AddressListProvider.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Why?

2022-10-13 09:23 UTC, mmiszy requested changes

2022-10-13 09:23 UTC, mmiszy commented on packages/checkout-storefront/src/hooks/useAlerts/useAlerts.tsx
> +    console.log(camelCase(keyBase));
```suggestion
```

2022-10-13 09:23 UTC, mmiszy commented on packages/checkout-storefront/src/sections/UserAddressSection/AddressListProvider.tsx
> +      console.log({ addressId });
```suggestion
```

2022-10-13 09:23 UTC, mmiszy commented on packages/checkout-storefront/src/sections/UserAddressSection/AddressListProvider.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Hmmm why?

2022-10-14 10:47 UTC, bmigirl commented on packages/checkout-storefront/src/hooks/useDynamicAppConfig.ts
> +  });
Pretty sure this was autofixed because it should stay as is, added comment

2022-10-14 10:58 UTC, bmigirl commented on packages/checkout-storefront/src/sections/Summary/SummaryItemMoneyEditableSection.tsx
> +    const isQuantityValid = !isNaN(quantity) && quantity >= 0;
Better safe than buggy, changing 😅

2022-10-14 11:03 UTC, witoszekdev approved these changes

2022-10-14 12:21 UTC, szczecha approved these changes

2022-10-14 18:53 UTC, mmiszy approved these changes

2022-10-14 18:53 UTC, merged