Video product gallery
saleor/react-storefront pull request #63
Opened 2021-11-02 16:38 UTC by IrgenKini

2021-11-03 10:09 UTC, krzysztofwolski requested changes

2021-11-03 10:09 UTC, krzysztofwolski commented on pages/products/[slug].tsx
> +  const youtube_parser = (url: string) => {
Should be moved to the lib/util.ts file

2021-11-03 10:09 UTC, krzysztofwolski commented on pages/products/[slug].tsx
> +  const youtube_parser = (url: string) => {
Rename to `getYouTubeIDFromURL`

2021-11-03 11:45 UTC, krzysztofwolski approved these changes

2021-11-03 11:46 UTC, merged

2021-11-05 12:52 UTC, patrys commented
Task linked: [SALEOR-4803 Videos in the product media gallery](https://app.clickup.com/t/2549495/SALEOR-4803)